# Generated by Django 4.1.4 on 2023-02-23 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('aff_name', models.CharField(max_length=250)),
                ('aff_email', models.EmailField(max_length=250)),
                ('aff_phone', models.CharField(max_length=12)),
                ('aff_subject', models.CharField(max_length=500)),
                ('aff_details', models.CharField(max_length=1250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
