# Generated by Django 4.1.4 on 2023-03-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_alter_affiliate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('SEEN', 'Seen'), ('FORWARDED', 'Forwarded'), ('CONVERTED', 'Converted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20),
        ),
    ]
