version: '4.1.4'

services:
  django:
    image: django-docker:0.0.1
    build: .
    ports: 
      - "80:8000"
    environment:
      - EMAIL_HOST_USER=manishsinghdewas02@gmail.com
      - EMAIL_HOST_PASSWORD=ietgdpxaxyzfcdpg


      
