# Generated by Django 4.1.4 on 2022-12-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_rename_message_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('facebook', models.CharField(max_length=1000)),
                ('instagram', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='agent_profile_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
