# Generated by Django 4.1.4 on 2022-12-21 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0003_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='facebook',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='agent',
            name='instagram',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=150)),
                ('agency_tagline', models.CharField(max_length=500)),
                ('agency_phone', models.CharField(max_length=12)),
                ('agency_email', models.EmailField(max_length=500)),
                ('agency_description', models.EmailField(max_length=5000)),
                ('agency_facebook', models.EmailField(blank=True, max_length=1000)),
                ('agency_instagram', models.EmailField(blank=True, max_length=1000)),
                ('agency_image', models.ImageField(upload_to='agency_profile_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
