# Generated by Django 4.1.4 on 2022-12-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_agency_agency_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('property_type', models.CharField(max_length=100)),
                ('property_status', models.CharField(max_length=100)),
                ('property_price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('pic_02', models.ImageField(upload_to='property_img_02')),
                ('main_pic', models.ImageField(upload_to='property_img_03')),
                ('agency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.agency')),
            ],
        ),
    ]
