# Generated by Django 4.1.4 on 2022-12-30 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pic_03',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='property_img_03'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='main_pic',
            field=models.ImageField(upload_to='main_property_img'),
        ),
    ]
