# Generated by Django 4.1.4 on 2023-01-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_size',
            field=models.CharField(default=4560, max_length=100),
            preserve_default=False,
        ),
    ]
