# Generated by Django 4.1.4 on 2023-01-04 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='auth_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
