# Generated by Django 4.1.4 on 2023-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_rename_loaction_maplocater_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocater',
            name='ip',
            field=models.CharField(default='115.240.90.163', max_length=50),
            preserve_default=False,
        ),
    ]
