# Generated by Django 4.1.4 on 2023-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_maplocater_user_maplocater_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='property_views', to='property.ipmodel'),
        ),
    ]
