# Generated by Django 4.1.4 on 2023-02-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_property_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_created_at',
        ),
    ]
