# Generated by Django 4.1.4 on 2023-03-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_remove_property_views_property_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='views',
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.TextField(default=None),
        ),
    ]
