# Generated by Django 4.1.4 on 2023-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_property_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.GenericIPAddressField(),
        ),
    ]
