# Generated by Django 4.1.4 on 2023-03-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_property_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='views',
        ),
    ]
